### your site title here
title: Xinyue (Evelyn) Zhao / 赵歆悦
description: Assistant Professor in Mathematics

# baseurl: "" #name of GitHub repository
# url: "" #custom url to be used instead of GitHub repository
# email: xzhao45@utk.edu

# highlighter: rouge
# markdown: kramdown

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
# facebook: "#"
# twitter: "#"
# linkedin: "lorenzocarnevale"
# github: "lcarnevale"
# researchgate: "#"
# orcid: "0000-0002-1349-341X"
# google_analytics: "G-V0TBR5PTVH"
# scopus: "57195963279"
# google_scholar: "_5EzmTwAAAAJ&hl=it"


# highlighter: rouge
# markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
# collections:
#   projects:
#     output: true
#     permalink: :path/projects/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _bibliography

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
